ındaki Source linklerini tarar ve indirir (Tarball buraya gelir)
	spectool -g -R specs/kernel.spec
	# İndirilen dosyaları ve spec'i kullanarak Kaynak RPM (SRPM) oluşturur
	rpmbuild -bs --define "_sourcedir $(PWD)/specs" --define "_srcrpmdir $(outdir)" specs/kernel.spec
